# Generated by Django 6.0.5 on 2026-05-18 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used', models.FloatField(default=0.0)),
                ('total_distance', models.FloatField(default=0.0)),
                ('total_duration', models.FloatField(default=0.0)),
                ('estimated_fuel_stops', models.IntegerField(default=0)),
                ('estimated_rest_stops', models.IntegerField(default=0)),
                ('estimated_trip_days', models.IntegerField(default=1)),
                ('is_hos_compliant', models.BooleanField(default=True)),
                ('route_geometry', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_type', models.CharField(choices=[('pickup', 'Pickup Location'), ('dropoff', 'Dropoff Location'), ('fuel', 'Fuel Stop'), ('break', 'HOS Rest Break'), ('rest', 'Overnight Sleep Stop'), ('sleeper', 'Sleeper Berth Rest')], max_length=50)),
                ('location_name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('arrival_time', models.DateTimeField()),
                ('departure_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(default=0)),
                ('fuel_required', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
        ),
    ]
